function searching(){
    var item=document.querySelector('#item');

    
    if(item.value=="260"){location.href="G260.HTML";}
    else if(item.value=="59"){location.href="G59.HTML";}
    else if(item.value=="71"){location.href="G71.HTML";}
    else if(item.value=="73"){location.href="G73.HTML";}
    else if(item.value=="76"){location.href="G76.HTML";}
    else if(item.value=="84"){location.href="G84.HTML";}
    else if(item.value=="86"){location.href="G86.HTML";}
    else if(item.value=="87"){location.href="G87.HTML";}
    else if(item.value=="89"){location.href="G89.HTML";}
    else if(item.value=="93"){location.href="G93.HTML";}
    else if(item.value=="94"){location.href="G94.HTML";}
    else if(item.value=="96"){location.href="G96.HTML";}
    else if(item.value=="101"){location.href="G101.HTML";}
    else if(item.value=="104"){location.href="G104.HTML";}
    else if(item.value=="118"){location.href="G118.HTML";}
    else if(item.value=="121"){location.href="G121.HTML";}
    else if(item.value=="125"){location.href="G125.HTML";}
    else if(item.value=="126"){location.href="G126.HTML";}
    else if(item.value=="129"){location.href="G129.HTML";}
    else if(item.value=="132"){location.href="G132.HTML";}
    else if(item.value=="137"){location.href="G137.HTML";}
    else if(item.value=="146"){location.href="G146.HTML";}
    else if(item.value=="167"){location.href="G167.HTML";}
    else if(item.value=="168"){location.href="G168.HTML";}
    else if(item.value=="436"){location.href="G436.HTML";}
    else if(item.value=="177"){location.href="G177.HTML";}
    else if(item.value=="180"){location.href="G180.HTML";}
    else if(item.value=="183"){location.href="G183.HTML";}
    else if(item.value=="183각할로"){location.href="G183각할로.HTML";}
    else if(item.value=="185"){location.href="G185.HTML";}
    else if(item.value=="186"){location.href="G186.HTML";}
    else if(item.value=="187"){location.href="G187.HTML";}
    else if(item.value=="189"){location.href="G189.HTML";}
    else if(item.value=="194"){location.href="G194.HTML";}
    else if(item.value=="195"){location.href="G195.HTML";}
    else if(item.value=="201"){location.href="G201.HTML";}
    else if(item.value=="203"){location.href="G203.HTML";}
    else if(item.value=="205"){location.href="G205.HTML";}
    else if(item.value=="214"){location.href="G214.HTML";}
    else if(item.value=="215"){location.href="G215.HTML";}
    else if(item.value=="217"){location.href="G217.HTML";}
    else if(item.value=="380"){location.href="G380.HTML";}
    else if(item.value=="381"){location.href="G381.HTML";}
    else if(item.value=="382"){location.href="G382.HTML";}
    else if(item.value=="383"){location.href="G383.HTML";}
    else if(item.value=="384"){location.href="G384.HTML";}
    else if(item.value=="386"){location.href="G286.HTML";}
    else if(item.value=="387"){location.href="G387.HTML";}
    else if(item.value=="388"){location.href="G388.HTML";}
    else if(item.value=="389"){location.href="G389.HTML";}
    else if(item.value=="390"){location.href="G390.HTML";}
    else if(item.value=="392"){location.href="G392.HTML";}
    else if(item.value=="393"){location.href="G393.HTML";}
    else if(item.value=="394"){location.href="G394.HTML";}
    else if(item.value=="396"){location.href="G396.HTML";}
    else if(item.value=="397"){location.href="G397.HTML";}
    else if(item.value=="398"){location.href="G398.HTML";}
    else if(item.value=="399"){location.href="G399.HTML";}
    else if(item.value=="401"){location.href="G401.HTML";}
    else if(item.value=="402"){location.href="G402.HTML";}
    else if(item.value=="403"){location.href="G403.HTML";}
    else if(item.value=="405"){location.href="G405.HTML";}
    else if(item.value=="407"){location.href="G407.HTML";}
    else if(item.value=="408"){location.href="G408.HTML";}
    else if(item.value=="409"){location.href="G409.HTML";}
    else if(item.value=="400"){location.href="G400.HTML";}
    else if(item.value=="410"){location.href="G410.HTML";}
    else if(item.value=="412"){location.href="G412.HTML";}
    else if(item.value=="413"){location.href="G413.HTML";}
    else if(item.value=="414"){location.href="G414.HTML";}
    else if(item.value=="415"){location.href="G415.HTML";}
    else if(item.value=="416"){location.href="G416.HTML";}
    else if(item.value=="417"){location.href="G417.HTML";}
    else if(item.value=="418"){location.href="G418.HTML";}
    else if(item.value=="419"){location.href="G419.HTML";}
    else if(item.value=="8464"){location.href="G8464.HTML";}
    else if(item.value=="435"){location.href="G435.HTML";}
    else if(item.value=="반파이프"){location.href="G반파이프.HTML";}
    else if(item.value=="별"){location.href="G별.HTML";}
    else if(item.value=="사각휘가르"){location.href="G사각휘가르.HTML";}
    else if(item.value=="사다리육각"){location.href="G사다리육각.HTML";}
    else if(item.value=="상젤리"){location.href="G상젤리.HTML";}
    else if(item.value=="숫자체인"){location.href="G숫자체인.HTML";}
    else if(item.value=="신체인"){location.href="G신체인.HTML";}
    else if(item.value=="HC"){location.href="GHC.HTML";}
    else if(item.value=="엘리M"){location.href="G엘리M.HTML";}
    else if(item.value=="잠자리"){location.href="G잠자리.HTML";}
    else if(item.value=="잠할"){location.href="G잠할.HTML";}
    else if(item.value=="정육각"){location.href="G정육각.HTML";}
    else if(item.value=="정육컷"){location.href="G정육컷.HTML";}
    else if(item.value=="체인"){location.href="G체인.HTML";}
    else if(item.value=="354"){location.href="G354.HTML";}
    else if(item.value=="355"){location.href="G355.HTML";}
    else if(item.value=="356"){location.href="G356.HTML";}
    else if(item.value=="357"){location.href="G357.HTML";}
    else if(item.value=="359"){location.href="G359.HTML";}
    else if(item.value=="360"){location.href="G360.HTML";}
    else if(item.value=="361"){location.href="G361.HTML";}
    else if(item.value=="362"){location.href="G362.HTML";}
    else if(item.value=="363"){location.href="G363.HTML";}
    else if(item.value=="365"){location.href="G365.HTML";}
    else if(item.value=="368"){location.href="G368.HTML";}
    else if(item.value=="369"){location.href="G369.HTML";}
    else if(item.value=="370"){location.href="G370.HTML";}
    else if(item.value=="371"){location.href="G371.HTML";}
    else if(item.value=="373"){location.href="G373.HTML";}
    else if(item.value=="374"){location.href="G374.HTML";}
    else if(item.value=="375"){location.href="G375.HTML";}
    else if(item.value=="453"){location.href="G453.HTML";}
    else if(item.value=="454"){location.href="G454.HTML";}
    else if(item.value=="455"){location.href="G455.HTML";}
    else if(item.value=="456"){location.href="G456.HTML";}
    else if(item.value=="458"){location.href="G458.HTML";}
    else if(item.value=="459"){location.href="G459.HTML";}
    else if(item.value=="460"){location.href="G460.HTML";}
    else if(item.value=="김혜수M"){location.href="G김혜수M.HTML";}
    else if(item.value=="377"){location.href="G377.HTML";}
    else if(item.value=="378"){location.href="G378.HTML";}
    else if(item.value=="379"){location.href="G379.HTML";}
    else if(item.value=="305"){location.href="G305.HTML";}
    else if(item.value=="판HC"){location.href="G판HC.HTML";}
    else if(item.value=="후지원"){location.href="G후지원.HTML";}
    else if(item.value=="186"){location.href="G186.HTML";}
    else if(item.value=="420"){location.href="G420.HTML";}
    else if(item.value=="421"){location.href="G421.HTML";}
    else if(item.value=="양면체인"){location.href="G양면체인.HTML";}
    else if(item.value=="향수메달"){location.href="G향수메달.HTML";}
    else if(item.value=="사발"){location.href="G사발.HTML";}
    else if(item.value=="육발"){location.href="G육발.HTML";}
    else if(item.value=="누드Q"){location.href="G누드Q.HTML";}
    else if(item.value=="422"){location.href="G422.HTML";}
    else if(item.value=="423"){location.href="G423.HTML";}
    else if(item.value=="424"){location.href="G424.HTML";}
    else if(item.value=="425"){location.href="G425.HTML";}
    else if(item.value=="426"){location.href="G426.HTML";}
    else if(item.value=="A311"){location.href="GA311.HTML";}
    else if(item.value=="A322"){location.href="GA322.HTML";}
    else if(item.value=="A331"){location.href="GA331.HTML";}
    else if(item.value=="A30"){location.href="GA30.HTML";}
    else if(item.value=="A31"){location.href="GA31.HTML";}
    else if(item.value=="A36"){location.href="GA36.HTML";}
    else if(item.value=="A43"){location.href="GA43.HTML";}
    else if(item.value=="A44"){location.href="GA44.HTML";}
    else if(item.value=="A39"){location.href="GA39.HTML";}
    else if(item.value=="A43"){location.href="GA43.HTML";}
    else if(item.value=="A46"){location.href="GA46.HTML";}
    else if(item.value=="A8"){location.href="GA8.HTML";}
    else if(item.value=="A40"){location.href="GA40HTML";}
    else if(item.value=="A42"){location.href="GA42.HTML";}
    else if(item.value=="A35"){location.href="GA35.HTML";}
    else if(item.value=="A37"){location.href="GA37.HTML";}
    else if(item.value=="A45"){location.href="GA45.HTML";}
    else if(item.value=="A38"){location.href="GA38.HTML";}
    else if(item.value=="B할로"){location.href="GB할로.HTML";}
    else if(item.value=="D6"){location.href="GD6.HTML";}
    else if(item.value=="F200"){location.href="GF200.HTML";}
    else if(item.value=="F208"){location.href="GF208.HTML";}
    else if(item.value=="LOVE"){location.href="GLOVE.HTML";}
    else if(item.value=="S체인"){location.href="GS체인.HTML";}
    else if(item.value=="각HC"){location.href="G각HC.HTML";}
    else if(item.value=="고HC"){location.href="G고HC.HTML";}
    else if(item.value=="구찌"){location.href="G구찌.HTML";}
    else if(item.value=="구찌B"){location.href="G구찌B.HTML";}
    else if(item.value=="금미사각"){location.href="G금미사각.HTML";}
    else if(item.value=="긴십자"){location.href="G긴십자.HTML";}
    else if(item.value=="김혜수M"){location.href="G김혜수M.HTML";}
    else if(item.value=="넓은체인"){location.href="G넓은체인.HTML";}
    else if(item.value=="농"){location.href="G농.HTML";}
    else if(item.value=="루이비통N"){location.href="G루이비통N.HTML";}
    else if(item.value=="만자"){location.href="G만자.HTML";}
    else if(item.value=="309"){location.href="G309.HTML";}
    else if(item.value=="310"){location.href="G310.HTML";}
    else if(item.value=="311"){location.href="G311.HTML";}
    else if(item.value=="312"){location.href="G312.HTML";}
    else if(item.value=="313"){location.href="G313.HTML";}
    else if(item.value=="314"){location.href="G314.HTML";}
    else if(item.value=="318"){location.href="G318.HTML";}
    else if(item.value=="321"){location.href="G321.HTML";}
    else if(item.value=="322"){location.href="G322.HTML";}
    else if(item.value=="324"){location.href="G324.HTML";}
    else if(item.value=="327"){location.href="G327.HTML";}
    else if(item.value=="328"){location.href="G328.HTML";}
    else if(item.value=="330"){location.href="G330.HTML";}
    else if(item.value=="336"){location.href="G336.HTML";}
    else if(item.value=="338"){location.href="G338.HTML";}
    else if(item.value=="339"){location.href="G339.HTML";}
    else if(item.value=="343"){location.href="G343.HTML";}
    else if(item.value=="345"){location.href="G345.HTML";}
    else if(item.value=="346"){location.href="G346.HTML";}
    else if(item.value=="348"){location.href="G348.HTML";}
    else if(item.value=="349"){location.href="G349.HTML";}
    else if(item.value=="352"){location.href="G352.HTML";}
    else if(item.value=="353"){location.href="G353.HTML";}
    else if(item.value=="285-1"){location.href="G285-1.HTML";}
    else if(item.value=="285-2"){location.href="G285-2.HTML";}
    else if(item.value=="300"){location.href="G300.HTML";}
    else if(item.value=="303"){location.href="G303.HTML";}
    else if(item.value=="304"){location.href="G304.HTML";}
    else if(item.value=="311"){location.href="G311.HTML";}
    else if(item.value=="236"){location.href="G236.HTML";}
    else if(item.value=="242"){location.href="G242.HTML";}
    else if(item.value=="245"){location.href="G245.HTML";}
    else if(item.value=="246"){location.href="G246.HTML";}
    else if(item.value=="322"){location.href="G322.HTML";}
    else if(item.value=="333"){location.href="G333.HTML";}
    else if(item.value=="357"){location.href="G357.HTML";}
    else if(item.value=="380-1"){location.href="G380-1.HTML";}
    else if(item.value=="391"){location.href="G391.HTML";}
    else if(item.value=="392"){location.href="G392.HTML";}
    else if(item.value=="393"){location.href="G393.HTML";}
    else if(item.value=="파이프"){location.href="G파이프.HTML";}
    else if(item.value=="파이프-1"){location.href="G파이프-1.HTML";}
    else if(item.value=="파이프-11"){location.href="G파이프-11.HTML";}
    else if(item.value=="파이프-3"){location.href="G파이프-3.HTML";}
    else if(item.value=="파이프-4"){location.href="G파이프-4.HTML";}
    else if(item.value=="파이프-5"){location.href="G파이프-5.HTML";}
    else if(item.value=="파이프-6"){location.href="G파이프-6.HTML";}
    else if(item.value=="파이프T자"){location.href="G파이프T자.HTML";}
    else if(item.value=="248"){location.href="G248.HTML";}
    else if(item.value=="250"){location.href="G250.HTML";}
    else if(item.value=="251"){location.href="G251.HTML";}
    else if(item.value=="253"){location.href="G253.HTML";}
    else if(item.value=="255"){location.href="G255.HTML";}
    else if(item.value=="235"){location.href="G235.HTML";}
    else if(item.value=="271"){location.href="G271.HTML";}
    else if(item.value=="256"){location.href="G256.HTML";}
    else if(item.value=="267"){location.href="G267.HTML";}
    else if(item.value=="264"){location.href="G264.HTML";}
    else if(item.value=="265"){location.href="G265.HTML";}
    else if(item.value=="273"){location.href="G273.HTML";}
    else if(item.value=="275"){location.href="G275.HTML";}
    else if(item.value=="277"){location.href="G277.HTML";}
    else if(item.value=="278"){location.href="G278.HTML";}
    else if(item.value=="279"){location.href="G279.HTML";}
    else if(item.value=="284"){location.href="G284.HTML";}
    else if(item.value=="285"){location.href="G285.HTML";}
    else if(item.value=="287"){location.href="G287.HTML";}
    else if(item.value=="288"){location.href="G288.HTML";}
    else if(item.value=="289"){location.href="G289.HTML";}
    else if(item.value=="291"){location.href="G291.HTML";}
    else if(item.value=="292"){location.href="G292.HTML";}
    else if(item.value=="294"){location.href="G294.HTML";}
    else if(item.value=="295"){location.href="G295.HTML";}
    else if(item.value=="299"){location.href="G299.HTML";}
    else if(item.value=="301"){location.href="G301.HTML";}
    else if(item.value=="302"){location.href="G302.HTML";}
    else if(item.value=="303"){location.href="G303.HTML";}
    else if(item.value=="306"){location.href="G306.HTML";}
    else if(item.value=="307"){location.href="G307.HTML";}
    else if(item.value=="판체인"){location.href="G판체인.HTML";}
    else if(item.value=="203-3"){location.href="G203-3.HTML";}
    else if(item.value=="228"){location.href="G228.HTML";}
    else if(item.value=="229"){location.href="G229.HTML";}
    else if(item.value=="224"){location.href="G224.HTML";}
    else if(item.value=="297"){location.href="G297.HTML";}
    else if(item.value=="433"){location.href="G433.HTML";}
    else if(item.value=="430"){location.href="G430.HTML";}
    else if(item.value=="431"){location.href="G431.HTML";}
    else if(item.value=="432"){location.href="G432.HTML";}


    else{
        alert("등록되지않았거나 없는 제품입니다.")
    }
}
